########################################
#
# TYPO3 boilerplate specific environment
# variable when using vagrant-docker-vm
# with reverse-proxy support.
#
########################################
# add as additional env_file if necesary
# to your corresponding docker-compose.yml
# file `- etc/environment.development.reverseproxy.yml`
# after `- etc/environment.development.yml`
#
# add to docker-compose.development-reverse-proxy.yml via:
#   within bash with installed moreutils:
#     `awk '/      - etc\/environment.development.yml/ && !x {print "      - etc/environment.development.reverseproxy.yml"; x=1} 1' docker-compose.development-reverse-proxy.yml|sponge docker-compose.development-reverse-proxy.yml`
########################################


# TYPO3
WEBDEVOPS_DEV_ENV=reverse-proxy
